lib/bloc/refund/refund_bloc.dart
lib/l10n/app_en.arb
lib/l10n/app_es.arb
lib/l10n/app_fi.arb
lib/l10n/app_fr.arb
lib/l10n/app_it.arb
lib/l10n/app_pt.arb
lib/routes/subswap/swap/get_refund/get_refund_page.dart
lib/routes/subswap/swap/get_refund/send_onchain.dart
lib/routes/subswap/swap/get_refund/wait_broadcast_dialog.dart
lib/routes/subswap/swap/get_refund/widgets/refund_item_action.dart
lib/routes/subswap/swap/get_refund/widgets/send_onchain_form.dart
lib/widgets/single_button_bottom_bar.dart

The progress dialog is not closing as we do not have a refund event. i.e. there is no `BreezEvent` to listen to know when the refund is done; the idea is to have one, or is the refund supposed to have a different flow @erdemyerebasmaz @roeierez ?

Plug refund bloc

---

lib/routes/withdraw_funds/withdraw_funds_address_page.dart
lib/routes/withdraw_funds/withdraw_funds_confirmation_confirm_button.dart

- Onchain balance is now being used for sweep
- Exception message is extracted from error

Sweep balance amount fix

---

lib/bloc/account/account_bloc.dart
lib/bloc/connectivity/connectivity_bloc.dart
lib/logger.dart
lib/routes/create_invoice/qr_code_dialog.dart
lib/routes/initial_walkthrough/mnemonics/verify_mnemonic_seed_page.dart
lib/routes/lnurl/payment/lnurl_payment_dialog.dart
lib/routes/lnurl/payment/lnurl_payment_page.dart
lib/routes/lnurl/payment/success_action/success_action_dialog.dart
lib/routes/lnurl/withdraw/lnurl_withdraw_dialog.dart
lib/routes/subswap/swap/swap_page.dart
lib/utils/exceptions.dart
lib/utils/payment_validator.dart

Testing some flows, I notice we are not extracting the error message we are showing to the user; this PR fixes it.

Improve exceptions by extracting its message and logging it

---

lib/l10n/app_en.arb
lib/l10n/app_es.arb
lib/l10n/app_fi.arb
lib/l10n/app_fr.arb
lib/l10n/app_it.arb
lib/l10n/app_pt.arb
lib/routes/qr_scan/widgets/qr_scan.dart
pubspec.lock
pubspec.yaml

Same thing as https://github.com/breez/breezmobile/pull/1035
Also bringing this fix https://github.com/breez/breezmobile/pull/986 
We should start thinking about how to share these shared components between breezmobile and cbreez.

Uses mobile scan instead of scan removing scan lib

---

lib/routes/initial_walkthrough/mnemonics/generate_mnemonic_seed_confirmation_page.dart

Pull from https://github.com/breez/breezmobile/pull/1036

Fix backup message height

---

lib/routes/lnurl/widgets/lnurl_metadata.dart

Same as https://github.com/breez/breezmobile/pull/987

Fix empty byte array image conversion

---

.github/workflows/build-ios.yml
.gitignore
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Runner.entitlements
lib/services/notifications.dart

The fix includes:
* Add entitlement file
* GoogleService-Info.plist file
* Firebase late initialization
* Disable strip symbols on release

Fix iOS build

---

lib/routes/lnurl/payment/lnurl_payment_page.dart
lib/routes/lnurl/withdraw/lnurl_withdraw_dialog.dart

This PR addresses https://github.com/breez/c-breez/issues/373

Correct the amount parsing on lnurlp & lnurlw when the amount isn't fixed

---

lib/routes/home/home_page.dart
lib/routes/splash/splash_page.dart
lib/routes/ui_test/ui_test_page.dart
lib/user_app.dart

Fixes https://github.com/breez/c-breez/issues/389

Do not display splash animation on startup unless it's initial launch

---

lib/routes/initial_walkthrough/initial_walkthrough.dart
lib/routes/initial_walkthrough/mnemonics/verify_mnemonic_seed_page.dart

Move to black theme right after walkthrough

---

lib/routes/security/widget/local_auth_switch.dart
lib/routes/security/widget/security_pin_management.dart
lib/widgets/designsystem/switch/simple_switch.dart

Pull the changes of https://github.com/breez/breezmobile/pull/1047

Add simple switch an uses it instead on pages that has a switch

---

lib/routes/initial_walkthrough/beta_warning_dialog.dart
lib/routes/initial_walkthrough/initial_walkthrough.dart
lib/routes/ui_test/ui_test_page.dart
pubspec.lock
pubspec.yaml

Fixes https://github.com/breez/c-breez/issues/396
|Before|After|
|---|---|
|![beta](https://user-images.githubusercontent.com/1225438/214070213-fa480a1c-3ddd-4c07-ad50-0d33b3fb9c71.png)|![alpha](https://user-images.githubusercontent.com/1225438/214070220-aedb4170-e5c3-410d-a090-1d71f8413777.png)|

Change beta warning to alpha warning

---

lib/bloc/account/account_bloc.dart

Simple strategy, on any foreground event limited to 1 per minute.
It will mitigate various scenarios that the app doesn't get notified immediately such as closed channels.
depends on https://github.com/breez/breez-sdk/pull/75

Sync periodically when app is moving to foreground

---

lib/bloc/network/network_settings_bloc.dart
lib/config.dart
lib/routes/network/widget/mempool_settings_widget.dart

Fixes https://github.com/breez/c-breez/issues/406

Show default url on Network api page

---

lib/theme/breez_dark_theme.dart

Fixes: https://github.com/breez/c-breez/issues/393
Affects primaryColor, button color, textButton foreground color and primaryIcon color.

Use Breez blue on dark theme

---

lib/bloc/account/account_bloc.dart

Fixes https://github.com/breez/c-breez/issues/398

Throw InsufficientLocalBalanceError properly when validating payment

---

lib/theme/theme_extensions.dart

Fixes: https://github.com/breez/c-breez/issues/392#event-8331940359
|Before|After|
|---|---|
|![old sats](https://user-images.githubusercontent.com/1225438/214139510-edd022cd-b30c-47f6-a722-8bf245c04479.png)|![new sats](https://user-images.githubusercontent.com/1225438/214139524-fa49d6a8-cdb0-4152-a1b1-a92c06ca3a58.png)|
|![old btc](https://user-images.githubusercontent.com/1225438/214139521-0d0b46a1-302d-44d7-a0c9-aca82e14cf74.png)|![new btc](https://user-images.githubusercontent.com/1225438/214139532-5056bfb8-5654-48d8-87a6-71faa7a73001.png)|
|![old hide](https://user-images.githubusercontent.com/1225438/214139518-31d8384e-7f44-47a2-ab4e-5f79c59f286a.png)|![new hide](https://user-images.githubusercontent.com/1225438/214139527-e822fa76-4607-45d2-b52f-1f8b8e1398de.png)|

Fix home header font spacing

---

lib/routes/subswap/swap/swap_page.dart
lib/routes/subswap/swap/widgets/address_widget_placeholder.dart

Fixes https://github.com/breez/c-breez/issues/407

Restyle QRCodePlaceholder to match Breezmobile UI

---

lib/routes/home/widgets/payments_list/payment_item_title.dart
pubspec.lock
pubspec.yaml

Related issue: https://github.com/breez/c-breez/issues/401
I did add more ways to extract possible descriptions, and I did set the fallback case to "Unknown"

Update payment title default to Unknown and expand extraction rules

---

lib/routes/home/widgets/status_text.dart

Fixes https://github.com/breez/c-breez/issues/386

Fix status text color

---

lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_description.dart
lib/routes/home/widgets/payments_list/payment_item_title.dart
lib/utils/extensions/payment_extensions.dart
test/utils/extensions/payment_extensions_test.dart

|Before|After|
|----|---|
|![before](https://user-images.githubusercontent.com/1225438/214588998-3ad25120-c346-427e-a53a-d038bc068ecb.png)|![after](https://user-images.githubusercontent.com/1225438/214589003-5d7c4ad9-a342-4d82-8821-b5954c46f08f.png)|

Extract description on payment dialog

---

lib/models/invoice.dart
lib/utils/extensions/breez_pos_message_extractor.dart
lib/utils/extensions/payment_extensions.dart
lib/widgets/payment_dialogs/payment_request_info_dialog.dart

Another one
|Before|After|
|---|---|
|![Screenshot_20230125-151329_Breez_Cloud](https://user-images.githubusercontent.com/1225438/214653212-d5446e55-bf25-44da-a402-785bcf8dd2bb.png)|![Screenshot_20230125-153745_Breez_Cloud](https://user-images.githubusercontent.com/1225438/214653201-42fda8f4-93d5-4138-93dc-6add5b3d1a22.png)|

Extract pos description on invoice

---

android/app/src/debug/AndroidManifest.xml
android/app/src/debug/res/values/strings.xml
android/app/src/main/AndroidManifest.xml
android/app/src/main/res/values/strings.xml
android/app/src/profile/AndroidManifest.xml
android/build.gradle

- Remove unnecessary manifests variations
- Move the app name to a strings resource
- Add a debug postfix on the app's name on debug variant
- Remove residual Huawei maven repo
Not doing:
- Updating the kotlin and gms plugin because for reason I'm getting the following error when trying to do it:
```
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
Searched Location: 
/Users/ademar/Workspace/c-breez/android/app/src/debug/google-services.json
/Users/ademar/Workspace/c-breez/android/app/src/google-services.json
/Users/ademar/Workspace/c-breez/android/app/src/Debug/google-services.json
/Users/ademar/Workspace/c-breez/android/app/google-services.json
```

Minor adjustments on the Android app

---

lib/bloc/currency/currency_state.dart

Align the list of default currencies with that of Breez Mobile.
Fixes #405
Tested and confirmed it works with local apk.

Update list of default currencies

---

lib/routes/subswap/swap/widgets/deposit_widget.dart

Addresses the point brought up here: https://github.com/breez/c-breez/issues/399#issuecomment-1404707113
Fixes #399

Fix fee warning handling when receiving on-chain

---

lib/bloc/user_profile/user_profile_bloc.dart
lib/services/notifications.dart

Fixes https://github.com/breez/c-breez/issues/387

Add a profile bloc logic to fill missing properties on user profile

---

lib/routes/home/widgets/no_lsp_widget.dart

Fixes https://github.com/breez/c-breez/issues/394

Fix no lsp widget theme

---

lib/routes/dev/commands.dart
lib/routes/dev/commands_list.dart
lib/routes/dev/widget/command.dart
lib/routes/dev/widget/render_body.dart

Converting functions that creates widgets into widgets

Broken widgets on dev page

---

lib/routes/create_invoice/create_invoice_page.dart
lib/routes/create_invoice/qr_code_dialog.dart
lib/routes/create_invoice/widgets/animated_background.dart
lib/routes/create_invoice/widgets/animation_progress.dart
lib/routes/create_invoice/widgets/animation_properties.dart
lib/routes/create_invoice/widgets/expiry_and_fee_message.dart
lib/routes/create_invoice/widgets/loading_or_error.dart
lib/routes/create_invoice/widgets/particle_model.dart
lib/routes/create_invoice/widgets/particle_painter.dart
lib/routes/create_invoice/widgets/particles_animations.dart
lib/routes/create_invoice/widgets/successful_payment.dart
lib/routes/create_invoice/widgets/successful_payment_dialog.dart
lib/routes/create_invoice/widgets/successful_payment_message.dart

Converting functions that create widgets into widgets

Broken widgets on create invoice

---

lib/bloc/user_profile/user_profile_bloc.dart
test/bloc/account_bloc_test.dart
test/unit_logger.dart
test/user_profile_bloc_test.dart
test/utils/hydrated_bloc_storage.dart

Fixes https://github.com/breez/c-breez/issues/459
I'm adding a "UnitLogTree" to take advantage of fimber on unit tests; it helped me a lot on these tests.

Fix user profile bloc unit tests

---

lib/routes/lnurl/payment/lnurl_payment_page.dart
lib/routes/lnurl/widgets/lnurl_metadata.dart

This PR references #409 
title, image location, button, no warning
Cosmetic fixes e5aabcd4fbf677ad00658ca152925908e159d401 and d5982f77f0f9f7e74a6ad473e577bec61c003619

409 lnurl UI

---

android/app/src/main/AndroidManifest.xml
ios/Runner/Info.plist
lib/bloc/input/input_bloc.dart

This fixes a race condition where the app did not parse lighting invoice when app where closed (not running in background).

fix issue with lnurl parcing on close #333

---

lib/bloc/account/payment_error.dart
lib/bloc/input/input_bloc.dart
lib/handlers/input_handler.dart
lib/routes/create_invoice/create_invoice_page.dart
lib/routes/lnurl/lnurl_invoice_delegate.dart
lib/routes/lnurl/payment/lnurl_payment_page.dart
lib/routes/lnurl/withdraw/lnurl_withdraw_dialog.dart
lib/routes/spontaneous_payment/spontaneous_payment_page.dart
lib/utils/exceptions.dart
lib/utils/payment_validator.dart
lib/widgets/payment_dialogs/payment_request_info_dialog.dart
pubspec.lock
pubspec.yaml
test/utils/exceptions_test.dart

Fixes https://github.com/breez/c-breez/issues/402
https://user-images.githubusercontent.com/1225438/217546049-7cad13ce-195c-47ce-9718-845005d19879.mp4
https://user-images.githubusercontent.com/1225438/217546057-1e6dbb7a-00ca-4944-b125-0dcbfa15033f.mp4
https://user-images.githubusercontent.com/1225438/217546069-abf8442b-86bf-4302-b68a-779205f53451.mp4

Replicate withdraw UX from Breez Mobile

---

README.md
conf/sample-breez.conf
lib/bloc/input/input_bloc.dart
lib/config.dart
lib/main.dart
lib/routes/home/widgets/payments_list/payments_list.dart
pubspec.lock

Took the opportunity to simplify the breez.conf file. Since the specific firebase files are required we don't need these additional parameters in the configuration anymore.
@ubbabeck  I found an in issue with the `_initializeInputBloc` function so took the opportunity to fix that.
Also added documentation for the firebase requirements.

Simplify config files

---

lib/routes/create_invoice/create_invoice_page.dart
lib/routes/create_invoice/qr_code_dialog.dart
lib/user_app.dart
lib/utils/exceptions.dart
pubspec.lock
pubspec.yaml
test/utils/exceptions_test.dart

I was trying to create a new wallet to debug out the newest bugs, and I got this error, so I'm fixing it before moving to the bug fixes.
I'm keeping the logs I added that helped me to understand the issue; let me know if you prefer me to remove them.
Also, I'm copying the replace error message for the localized ones we did add to breez mobile.
To change the error message, update this entry https://github.com/breez/Breez-Translations/blob/main/lib/app_en.arb#L2278 or send me the better text for me to update it.
|Before|After|
|---|---|
|![before](https://user-images.githubusercontent.com/1225438/220388022-3107ba92-e3f8-46c1-8a4b-e08941a4c1db.png)|![after](https://user-images.githubusercontent.com/1225438/220388032-a0e48a72-5ef9-44c2-a353-27513dcf2a2b.png)|

Fix network message

---

lib/bloc/account/payment_result.dart
lib/bloc/swap_in/swap_in_bloc.dart
lib/bloc/withdraw/withdraw_funds_bloc.dart
lib/handlers/input_handler.dart
lib/routes/create_invoice/qr_code_dialog.dart
lib/routes/initial_walkthrough/initial_walkthrough.dart
lib/routes/initial_walkthrough/mnemonics/widgets/restore_form_page.dart
lib/routes/lnurl/payment/pay_response.dart
lib/routes/lnurl/payment/success_action/success_action_dialog.dart
lib/routes/lnurl/withdraw/lnurl_withdraw_dialog.dart
lib/routes/subswap/swap/get_refund/wait_broadcast_dialog.dart
lib/routes/withdraw_funds/confirmation_page/widgets/sweep_button.dart
lib/utils/exceptions.dart
lib/utils/payment_validator.dart
test/utils/exceptions_test.dart

Fixes: https://github.com/breez/c-breez/issues/506
Pulls the payment error messages from breez mobile.
Waiting for https://github.com/breez/c-breez/pull/504 merges to make a real-world test; if the message is a little bit different from the messages I did write on the unit test which I take from the issue, a minor change will be needed on the extraction logic.

Extract Ln payments error messages

---

lib/bloc/account/payment_result.dart
lib/handlers/input_handler.dart
lib/handlers/payment_result_handler.dart
lib/routes/home/home_page.dart

Removed currency bloc and it's remnants from PaymentResultHandler.
Corrected a typo on _handleLNURLPaymentPageResult logs

Remove unused bloc from PaymentResultHandler

---

lib/routes/payment_options/payment_options_page.dart
lib/routes/payment_options/widget/actions_fee.dart
lib/routes/payment_options/widget/base_fee_widget.dart
lib/routes/payment_options/widget/header_fee.dart
lib/routes/payment_options/widget/override_fee.dart
lib/routes/payment_options/widget/payment_option_warning.dart
lib/routes/payment_options/widget/proportional_fee_widget.dart
lib/routes/payment_options/widget/save_dialog.dart

Related: https://github.com/breez/c-breez/issues/267
How it looks like:

Pull widgets from breez mobile changing them from methods to classes

---

lib/routes/home/widgets/payments_list/payment_item_amount.dart
lib/routes/home/widgets/payments_list/payment_item_subtitle.dart
lib/routes/home/widgets/payments_list/payment_item_title.dart
lib/routes/home/widgets/payments_list/payments_list.dart
pubspec.lock
pubspec.yaml
test/config_test.dart
test/mock/breez_bridge_mock.dart
test/models/payment_minutiae_test.dart

- Updated dependencies to latest
- Use const for instantiating constant constructors to improve performance
- Depends on https://github.com/breez/breez-sdk/pull/148

Update dependencies to latest

---

ios/Runner/Info.plist
lib/bloc/user_profile/default_profile_generator.dart
lib/bloc/user_profile/profile_animal.dart
lib/bloc/user_profile/profile_color.dart
lib/utils/date.dart
pubspec.lock
pubspec.yaml

Thank you @CS-HODL for adding the translation 🙏

Add sk translation

---

lib/bloc/payment_options/payment_options_bloc.dart
lib/bloc/payment_options/payment_options_state.dart
lib/main.dart
lib/utils/preferences.dart
test/bloc/payment_options/payment_options_bloc_test.dart
test/mock/preferences_mock.dart
test/utils/preferences_test.dart

Add the bloc and the preferences that store the user options, related: https://github.com/breez/c-breez/issues/267

Payment options bloc and preferences

---

lib/bloc/payment_options/form_validator.dart
lib/bloc/payment_options/payment_options_bloc.dart
lib/bloc/payment_options/payment_options_state.dart
lib/main.dart
lib/routes/payment_options/payment_options_page.dart
lib/routes/payment_options/widget/actions_fee.dart
lib/routes/payment_options/widget/base_fee_widget.dart
lib/routes/payment_options/widget/override_fee.dart
lib/routes/payment_options/widget/proportional_fee_widget.dart
lib/routes/payment_options/widget/save_dialog.dart
lib/utils/preferences.dart
test/bloc/payment_options/form_validator_test.dart
test/bloc/payment_options/payment_options_bloc_test.dart
test/mock/preferences_mock.dart
test/utils/preferences_test.dart

related: https://github.com/breez/c-breez/issues/267
How it looks like:
https://user-images.githubusercontent.com/1225438/225344778-a6c3af17-912c-4f81-ad8e-11164f50a03a.mp4

Bind payments override bloc and widgets

---

lib/bloc/withdraw/withdraw_funds_bloc.dart
lib/routes/withdraw_funds/confirmation_page/widgets/sweep_button.dart
lib/routes/withdraw_funds/confirmation_page/withdraw_funds_confirmation_page.dart

This PR addresses the parameter name change in 
- https://github.com/breez/breez-sdk/pull/242

Update sweep feerate unit to sats per vbyte

---

android/build.gradle
lib/bloc/buy_bitcoin/moonpay/moonpay_bloc.dart
lib/bloc/buy_bitcoin/moonpay/moonpay_state.dart
lib/main.dart
lib/routes/buy_bitcoin/moonpay/moonpay_error.dart
lib/routes/buy_bitcoin/moonpay/moonpay_loading.dart
lib/routes/buy_bitcoin/moonpay/moonpay_page.dart
lib/routes/buy_bitcoin/moonpay/moonpay_swap_in_progress.dart
lib/routes/buy_bitcoin/moonpay/moonpay_webview.dart
lib/routes/home/widgets/bottom_actions_bar/receive_options_bottom_sheet.dart
lib/user_app.dart
lib/utils/exceptions.dart
pubspec.lock
pubspec.yaml
test/utils/exceptions_test.dart

Related: https://github.com/breez/breez-sdk/pull/189 and https://github.com/breez/breez-sdk/pull/208
Fixes: https://github.com/breez/c-breez/issues/560

Buy Bitcoin with Moonpay

---

lib/bloc/account/account_bloc.dart
lib/bloc/ext/block_builder_extensions.dart
lib/bloc/withdraw/withdraw_funds_bloc.dart
lib/bloc/withdraw/withdraw_funds_state.dart
lib/routes/dev/commands_list.dart
lib/routes/dev/widget/render_body.dart
lib/routes/home/widgets/app_bar/account_required_actions.dart
lib/routes/home/widgets/bottom_actions_bar/send_options_bottom_sheet.dart
lib/routes/withdraw_funds/confirmation_page/withdraw_funds_confirmation_page.dart
lib/routes/withdraw_funds/widgets/bitcoin_address_text_form_field.dart
lib/routes/withdraw_funds/widgets/withdraw_amount_text_form_field.dart
lib/routes/withdraw_funds/widgets/withdraw_funds_address_next_button.dart
lib/routes/withdraw_funds/widgets/withdraw_funds_available_btc.dart
lib/routes/withdraw_funds/withdraw_funds_address_page.dart
lib/user_app.dart
lib/utils/payment_validator.dart
lib/utils/validator_holder.dart
lib/widgets/amount_form_field/sat_amount_form_field_formatter.dart

Some work on: https://github.com/breez/c-breez/issues/148 still need to integrate to the library to make the send works.
This commit e952f00b2fa7549e747a2d99ac5eaba107aea457 fixes the https://github.com/breez/c-breez/issues/570 issue
https://github.com/breez/c-breez/assets/1225438/64853851-41cd-4046-be00-b33c8ad9876b

Send to BTC Address

---

lib/routes/home/widgets/bottom_actions_bar/receive_options_bottom_sheet.dart

This PR addresses https://github.com/breez/c-breez/issues/597#issuecomment-1635769130

Remove maxChannelReserve message from UI

---

integration_test/breez_sdk_test.dart
lib/background/breez_service_initializer.dart
lib/background/payment_hash_poller.dart
lib/bloc/account/account_bloc.dart
lib/bloc/backup/backup_bloc.dart
lib/bloc/buy_bitcoin/moonpay/moonpay_bloc.dart
lib/bloc/currency/currency_bloc.dart
lib/bloc/input/input_bloc.dart
lib/bloc/lsp/lsp_bloc.dart
lib/bloc/refund/refund_bloc.dart
lib/bloc/swap_in/swap_in_bloc.dart
lib/bloc/withdraw/withdraw_funds_bloc.dart
lib/config.dart
lib/main.dart
lib/routes/dev/commands_list.dart
lib/routes/home/widgets/app_bar/account_required_actions.dart
lib/routes/home/widgets/enable_backup_dialog.dart
lib/routes/home/widgets/payments_list/payment_item_amount.dart
lib/routes/home/widgets/payments_list/payments_list.dart
lib/routes/subswap/swap/swap_page.dart
lib/services/injector.dart
lib/user_app.dart
pubspec.lock
test/bloc/account/account_bloc_test.dart
test/bloc/input/input_bloc_test.dart
test/mock/breez_bridge_mock.dart
test/mock/injector_mock.dart

This PR applies changes in 
- https://github.com/breez/breez-sdk/pull/350

BreezSDK naming changes

---

lib/bloc/account/account_state.dart
lib/routes/subswap/swap/widgets/deposit_widget.dart
lib/widgets/receivable_btc_box.dart
pubspec.lock
pubspec.yaml

Applying https://github.com/breez/breezmobile/issues/1179 to C-breez.

Don't display setup fees when not needed

---

pubspec.lock
test/config_test.dart
test/mock/breez_bridge_mock.dart

Depends on https://github.com/breez/breez-sdk/pull/451
Adds required params to the sdkConfig.

Expose exemptfee

---

lib/bloc/account/account_bloc.dart
lib/bloc/csv_exporter.dart
lib/routes/home/widgets/payments_filter/payment_filter_exporter.dart
lib/routes/home/widgets/payments_filter/payments_filter.dart
lib/routes/home/widgets/payments_filter/payments_filter_calendar.dart
lib/utils/date.dart
pubspec.lock
pubspec.yaml

This pr is going to add the ability for the user to export their payment history to a csv file.

 535 export to csv is missing

---

android/app/build.gradle

Copy the signing config from breez mobile

Add signing config

---

lib/routes/qr_scan/widgets/qr_scan.dart

Applies https://github.com/breez/breezmobile/pull/1220 changes

Fix safe area on qr code read page

---

lib/handlers/input_handler.dart

Fixes #645
(Draft, as it's not tested yet).

Call correct arg when handling LNURL

---

lib/routes/home/widgets/app_bar/account_required_actions.dart

add refunds to warnings

---

lib/routes/dev/command_line_interface.dart
lib/routes/dev/widget/command_list.dart

Tested with https://github.com/breez/breez-sdk/pull/513
Fixes #656

Add GetInfo node command

---

lib/routes/initial_walkthrough/mnemonics/widgets/restore_form.dart

Since I went through this screen a lot for other tests, I wanted to fix a few things that bothered me:
- Don't show autosuggestions when the input field is empty
- Fix autosuggestion box flickering

Recover screen fixes

---

lib/routes/home/widgets/drawer/breez_avatar_dialog.dart

Also added some logs to help debug future issues.
- Open the hamburger menu
- Touching at your avatar
- Change your avatar (repeat this process with the variations:)
- Random
- Gallery
- Select gallery but back without selecting a file
- Cancel the crop process
- Try saving and not saving after the changes
- The app should never crash

Fix avatar crash when selecting an invalid file

---

lib/routes/withdraw/reverse_swap/confirmation_page/widgets/reverse_swap_button.dart
lib/routes/withdraw/reverse_swap/in_progress/reverse_swap_in_progress.dart

go back to home page on success
fixes #653

use blockexplorer from config

---

.github/workflows/CI.yml

forgot to revert the change before mergning...

revert to use main branch

---

lib/routes/create_invoice/create_invoice_page.dart
lib/routes/lnurl/payment/lnurl_payment_page.dart

31efea9d2f858ac489fb701169101d0bae4c5fd5 ensures that we display the selected bitcoin denomination
8a9c27d15ebb710c984bd5c68f2c491027d2250b makes lnurlp min and max clickable as in breezmobile.

689 lnurlp and lnurlw

---

lib/widgets/receivable_btc_box.dart

watch lsp state instead

---

.gitignore

ignore .env and .envrc

---

android/app/build.gradle
lib/background/payment_hash_poller.dart
lib/bloc/account/account_bloc.dart
lib/bloc/account/payment_filters.dart
lib/bloc/csv_exporter.dart
lib/routes/home/account_page.dart
lib/routes/home/widgets/payments_filter/payment_filter_exporter.dart
lib/routes/home/widgets/payments_filter/payments_filter.dart
lib/routes/home/widgets/payments_filter/payments_filter_calendar.dart
lib/routes/home/widgets/payments_filter/payments_filter_sliver.dart
lib/routes/withdraw/reverse_swap/confirmation_page/reverse_swap_confirmation_page.dart

use PaymentTypeFilter as list

---

ios/Runner/Info.plist
lib/bloc/user_profile/default_profile_generator.dart
lib/bloc/user_profile/profile_animal.dart
lib/bloc/user_profile/profile_color.dart
lib/utils/date.dart
pubspec.lock
pubspec.yaml

Thank you @ch0k1 and @Nackoo2000 for the translations
How it looks like
|||||
|---|---|---|---|
|![payment](https://github.com/breez/c-breez/assets/1225438/ec411f81-4e75-4ab4-8e4e-d4ce9f56e88f)|![drawer](https://github.com/breez/c-breez/assets/1225438/a358d20d-4024-4bdb-8da4-fba2a5b045f9)|![home](https://github.com/breez/c-breez/assets/1225438/ae57f3f2-4875-47c7-b812-e8b2dace4c0a)|![lock](https://github.com/breez/c-breez/assets/1225438/8ae4396c-5df1-45e8-839c-a538b0eb0dc0)|

Add bulgarian language 💪 🇧🇬🇪🇺🇦🇱🇨🇿🇭🇺🇲🇩🇷🇴🇷🇺🇷🇸🇹🇷🇺🇦 🚀 

---

lib/bloc/account/account_bloc.dart
lib/bloc/csv_exporter.dart
lib/bloc/network/network_settings_bloc.dart
lib/routes/home/account_page.dart
lib/routes/home/widgets/payments_filter/payment_filter_exporter.dart
lib/routes/home/widgets/payments_filter/payments_filter.dart

- fixes issue with multiple filters not being possible
- use only one filtering function
- Filter payments in UI
- Export payments

refactor csv export and payment filtering

---

lib/bloc/account/account_bloc.dart
lib/logger.dart
test/mock/breez_bridge_mock.dart

Fixes https://github.com/breez/c-breez/issues/694
The app loses connection to the SDK once it gets in the background and it is not able to reconnect once it is back.
A way to reproduce it is by minimizing the app and interacting with other apps; you may need to open several apps or heavy apps if you are using a high-end device; once the system has enough pressure to deactivate the app you will experience the bug.
The solution I'm bringing on this PR is to disconnect the SDK once the app is paused and connect once it is started or resumed.
I've tested in several scenarios using the clipboard as the "way of checking" but you can try any other functionalities; it is not a clipboard issue at all; it is a lifecycle issue; by doing the clipboard I'm just showing it is working for …

Fix lifecycle issues with sdk connection

---

android/app/build.gradle
ios/Podfile.lock
lib/logger.dart
lib/routes/create_invoice/qr_code_dialog.dart
lib/routes/ui_test/ui_test_page.dart
pubspec.lock
pubspec.yaml

- **Required:** Add missing minFinalCltvExpiryDelta to placeholder LNInvoice used on tests 89b4a6b
- Update dependencies to latest 7b903d56ee306045621108d892a78e1d1a86c3af
- Use debug signing config on debug mode ec2779519ff5ba080e8af4ddd783a50c6529b45a
- This was set set development by mistake
- Release versions are currently built using debug signing config (@roeierez) 
- Don't compute extract exception message when error is null 65effd18f2a350af34f97509a4d9795eb675ba2d 
- This threw a misleading false positive exception in logs as it was being computed even if error was null
-  Increase logger level to CONFIG d6ec196ec30d614d936a3762fec44e845f71bd07
- We were missing debug logs from the SDK

Update dependencies to latest and address minor issues

---

lib/bloc/fee_options/fee_options_bloc.dart
lib/bloc/reverse_swap/reverse_swap_bloc.dart
lib/bloc/reverse_swap/reverse_swap_state.dart
lib/routes/withdraw/reverse_swap/reverse_swap_page.dart

Also moved the `fetchReverseSwapOptions` to the reverse swap bloc. I think it belongs there.

Integrate send all funds

---

lib/bloc/fee_options/fee_options_bloc.dart
lib/bloc/sweep/sweep_bloc.dart
lib/routes/withdraw/sweep/confirmation_page/sweep_confirmation_page.dart
lib/routes/withdraw/sweep/confirmation_page/widgets/sweep_button.dart

introduced https://github.com/breez/breez-sdk/pull/603 breaking changes.
Do we wish to postpone this pr for the upcoming c-breez release and instead use the https://github.com/breez/breez-sdk-flutter/releases/tag/v0.2.9. For this release ?
@erdemyerebasmaz @roeierez

use satPerVbyte

---

ios/Breez Notification Service Extension/BreezManager.swift
ios/Breez Notification Service Extension/CredentialsManager.swift
ios/Breez Notification Service Extension/Environment.swift
ios/Breez Notification Service Extension/Info.plist
ios/Breez Notification Service Extension/NotificationService.swift
ios/Runner.xcodeproj/project.pbxproj
lib/services/keychain.dart

An attempt to simplify things a bit.

Use simple approach for ios notifications handling

---

ios/Podfile.lock
pubspec.lock
pubspec.yaml

This PR is counterpart of 
- https://github.com/breez/breez-sdk/pull/669
- Update dependencies to latest resolvable

Update flutter_rust_bridge to 1.82.4

---

ios/Podfile.lock
pubspec.lock
pubspec.yaml

Update flutter_rust_bridge to 1.82.6

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/cBreez/client/BreezFCMService.kt
android/app/src/main/java/com/cBreez/client/BreezLogger.kt
android/app/src/main/java/com/cBreez/client/BreezNotificationService.kt
android/app/src/main/java/com/cBreez/client/BreezSdkConnector.kt
android/app/src/main/java/com/cBreez/client/BreezSdkWorker.kt
android/app/src/main/java/com/cBreez/client/JobManager.kt
android/app/src/main/java/com/cBreez/client/RSACihper18Implementation.kt
android/app/src/main/kotlin/com/cBreez/client/MainActivity.kt
android/app/src/main/resources/tinylog.properties
ios/Breez Notification Service Extension/NotificationService.swift
lib/logger.dart

This PR adds logging capability to notification service on Android.
Notifications for received payments now click app when clicked and are dismissable.

Android notifications logging

---

pubspec.lock

bump dependencies

---

lib/bloc/health_check/health_check_bloc.dart
lib/handlers/health_check_handler.dart
lib/main.dart
lib/routes/home/home_page.dart
lib/widgets/flushbar.dart
pubspec.lock
pubspec.yaml
test/bloc/health_check/health_check_bloc_test.dart
test/mock/breez_bridge_mock.dart

Implement Health Check Status
Fixes https://github.com/breez/c-breez/issues/729
|Maintanance|Service disruption|
|:-:|:-:|
|![maintanance](https://github.com/breez/c-breez/assets/1225438/c68693ed-eaf2-4f5d-aef0-df70b148b26c)|![disruption](https://github.com/breez/c-breez/assets/1225438/169495c1-8723-4e52-97ee-bf3576e40682)|
- Change the code to emit a different `HealthCheckStatus` than `Operational`
- You should see at the home page a flushbar like that one in screenshot
- Wait for a moment in the future when breez service is in maintenance or has it service disrupted
- You should see at the home page a flushbar like that one in screenshot

Implement Health Check Status

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/com/cBreez/client/BreezForegroundService.kt
android/app/src/main/kotlin/com/cBreez/client/BreezNotificationHelper.kt
ios/Podfile.lock
lib/routes/home/home_page.dart
lib/user_app.dart
pubspec.lock
pubspec.yaml

Open the app without making a preferred app selection upon clicking a payment received notification.
- Applies changes to remote message payload introduced on 
https://github.com/breez/notify/pull/10
- Update dependencies to latest
- Correct NavigatorPopHandler behaviour

Open the app upon clicking a payment received notification

---

pubspec.lock
pubspec.yaml

Diff of translations: https://github.com/breez/Breez-Translations/compare/ba8d9bd644a013521389d225bb6850dcd4a2918f..601b0cdcea3a7138a1c4339960985947fcc61ece

Update breez translations

---

.github/workflows/build-ios.yml
lib/routes/initial_walkthrough/initial_walkthrough.dart
lib/routes/splash/splash_page.dart

766 UI problem

---

ios/Podfile.lock
pubspec.lock
test/mock/breez_bridge_mock.dart

*adds new pending balance field to node state.
*update dependencies

add pending balance field

---

.github/workflows/CI.yml
.github/workflows/build-android.yml
.github/workflows/build-ios.yml

Allow setting optional checkout reference for SDK on CI workflows

---

lib/bloc/account/account_bloc.dart
test/mock/breez_bridge_mock.dart

Use `ConnectRequest` when calling `connect`
SDK PR https://github.com/breez/breez-sdk/pull/790

Change `connect` params

---

android/app/src/main/kotlin/com/cBreez/client/job/LnurlPayInfo.kt
android/app/src/main/kotlin/com/cBreez/client/job/LnurlPayInvoice.kt

The response field names should be camel cased

Fix the serialization of the LNURL-pay responses

---

android/app/src/main/kotlin/com/cBreez/client/BreezFcmService.kt
android/app/src/main/kotlin/com/cBreez/client/BreezForegroundService.kt
android/app/src/main/kotlin/com/cBreez/client/BreezNotificationHelper.kt
android/app/src/main/kotlin/com/cBreez/client/Constants.kt
android/app/src/main/kotlin/com/cBreez/client/job/RedeemSwap.kt
android/app/src/main/res/values/string.xml
lib/bloc/swap_in_progress/swap_in_progress_bloc.dart

Handle notifications for swap txs

---

ios/Breez Notification Service Extension/BgTasks/RedeemSwap.swift

Add argument label to redeemSwap call

Fix SDK call to redeemSwap

---

lib/routes/create_invoice/widgets/loading_or_error.dart
lib/routes/home/widgets/bottom_actions_bar/receive_options_bottom_sheet.dart
lib/routes/home/widgets/drawer/breez_avatar_dialog.dart
lib/routes/lightning_address/lightning_address_page.dart
lib/widgets/address_widget.dart

Add Lightning Address translations and remove unwanted artifacts from spinner

---

lib/bloc/swap_in_progress/swap_in_progress_bloc.dart

Closes #808
- Stop polling once swap in progress is waiting for confirmation
- Increase swap refresh interval to 30 seconds

Minimize swap address polling

---

lib/bloc/health_check/health_check_bloc.dart
lib/config.dart
test/mock/breez_bridge_mock.dart

Use the static `service_health_check` from PR https://github.com/breez/breez-sdk/pull/856

Adapt serviceHealthCheck usage

---

lib/bloc/webhooks/webhooks_bloc.dart
lib/bloc/webhooks/webhooks_state.dart
lib/main.dart
lib/routes/lightning_address/lightning_address_page.dart
lib/routes/lightning_address/ln_address_widget.dart
lib/routes/subswap/swap/swap_page.dart
lib/routes/subswap/swap/widgets/swap_error_message.dart
lib/utils/preferences.dart
lib/widgets/receivable_btc_box.dart

Brings "Receive via Lightning Address" page & WebhooksBloc consistent with other receive option pages & blocs.
Considers the fee limit when displaying maximum receivable amount

LN Address page rework

---

.github/workflows/build-android.yml
android/app/build.gradle

This PR enables release build with a predefined signing key that can come either from one of these inputs:
1. key properties file (key.properties)
2. environment variables - to run from CI

Android release build

---

lib/routes/create_invoice/widgets/loading_or_error.dart

Fix invoice CircularProgressIndicator artifacts

---

lib/bloc/input/input_bloc.dart
lib/bloc/input/input_printer.dart
lib/bloc/input/input_state.dart
lib/bloc/network/network_settings_bloc.dart
lib/bloc/swap_in_progress/swap_in_progress_bloc.dart
lib/bloc/swap_in_progress/swap_in_progress_state.dart
lib/config.dart
lib/logger.dart
lib/main.dart
lib/routes/get-refund/widgets/refund_item_action.dart
lib/routes/home/widgets/payments_list/dialog/closed_channel_payment_details.dart
lib/routes/qr_scan/widgets/qr_scan.dart
lib/routes/subswap/swap/swap_page.dart
lib/routes/withdraw/reverse_swap/in_progress/reverse_swap_in_progress.dart
lib/utils/sdk_fields/serializer_helper.dart
test/bloc/input/input_bloc_test.dart

- Revise swap in progress bloc & state
- Ensure the bloc isn't closed when emitting states
- Don't stop polling even if swap in progress is waiting for confirmation
-  SwapPage: Swap in progress widget takes precedence over deposit address widget

Refactor swap in progress

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
pubspec.lock
pubspec.yaml

Adds missing extension source under Compile Sources
- Update dependencies to latest.

Add extensions `PrivacyInfo.xcprivacy` to Compile Sources

---

lib/bloc/rev_swap_in_progress/rev_swap_in_progress_bloc.dart
lib/bloc/swap_in_progress/swap_in_progress_bloc.dart

- Regression: Replace function reference with function call
- Remove async logic
- Hide loader for background refreshes

Fix background polling on swap pages

---

lib/routes/dev/command_line_interface.dart
lib/routes/dev/widget/command_list.dart

[![Run CI](https://github.com/breez/c-breez/actions/workflows/CI.yml/badge.svg?branch=diagnostics_command)](https://github.com/breez/c-breez/actions/workflows/CI.yml?branch=diagnostics_command)
---
Closes https://github.com/breez/c-breez/issues/877
Breez SDK PR: 
- https://github.com/breez/breez-sdk/pull/929

Add `generateDiagnosticData` command to developer panel

---

lib/routes/ln_address/ln_address_fee_message.dart

Display error message if LSP cannot open a new channel on LN Address page

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj

This PR updates the XCode compile sources to reflect the changes in PR https://github.com/breez/breez-sdk/pull/937, which merges the BreezSDK and BreezSDKNotification source directories together to fix import issues when using breez-sdk-swift via the Swift Package Manager

Update compile sources

---

android/app/src/main/AndroidManifest.xml
lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_description.dart

Do not display subtitle if it's the same with title on payment details dialog
Disable application backup on Android

Do not display subtitle if it's the same with title on payment details dialog

---

.github/workflows/build-android.yml

This PR:
- Updates the macOS runner
- Installs the needed cross compilation tools
CI builds:
- Android: https://github.com/breez/c-breez/actions/runs/14948351665
- iOS: https://github.com/breez/c-breez/actions/runs/14948620683

Updates for Uniffi 0.28

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
lib/bloc/account/credentials_manager.dart
lib/logger.dart
lib/routes/create_invoice/qr_code_dialog.dart
lib/routes/dev/command_line_interface.dart
lib/routes/dev/developers_view.dart
lib/routes/home/widgets/payments_filter/payment_filter_exporter.dart
lib/routes/home/widgets/payments_list/dialog/shareable_payment_row.dart
lib/routes/spontaneous_payment/widgets/collapsible_list_item.dart
lib/routes/subswap/swap/widgets/subswap_dialog.dart
lib/services/device.dart
lib/services/injector.dart
lib/services/wallet_archive_service.dart
lib/utils/overlay_manager.dart
lib/widgets/address_widget.dart
pubspec.lock
pubspec.yaml

This PR migrates archive & share_plug packages to latest to address issues w/ compressing log files.
This PR also brings certain services & utilities from Misty Breez.
- Created `OverlayManager` to manage loading overlay while exporting logs & keys.
- Created `WalletArchiveService` that's responsible for creating archive files.
- Phrase file is now a *.txt file.
- Moved `CredentialsManager` to `ServiceInjector` so it's globally accessible.
- Added feedback to the user for developer menu item actions regarding their status

update archive & share_plus to latest to address issues w/ compressing log files
