breez/c-breez

- android/app/src/main/AndroidManifest.xml
We move to singleTask instead of singleTop. 
Main difference is that singleTask behaves like a single top with one activity instance and singleTop may create several activity instances.
In the app we are not prepared (and do not want) several instances of the main activity which will result in multiple initializations of the rust sdk.
https://developer.android.com/guide/topics/manifest/activity-element#aff
> Use singleTask activity

- lib/routes/home/widgets/app_bar/account_required_actions.dart
- lib/routes/home/widgets/bottom_actions_bar/send_options_bottom_sheet.dart
- lib/routes/withdraw_funds/withdraw_funds_address_page.dart
- lib/user_app.dart
Send to BTC flow has 2 possible titles, one when the user spontaneously send its sats to a BTC address and another when he needs to refund after a channel closed, this PR I add a way to correctly set the title on send to BTC flow
> Fix send to btc title

- lib/bloc/account/account_bloc.dart
- lib/routes/lnurl/payment/lnurl_payment_dialog.dart
- lib/routes/lnurl/payment/lnurl_payment_page.dart
- lib/routes/lnurl/withdraw/lnurl_withdraw_dialog.dart
This PR addresses https://github.com/breez/c-breez/issues/374
A generic error message "Failed to receive funds" is shown for unexpected errors thrown during lnurl withdraw flow.
> Return generic error message for unexpected errors on lnurlw flow

- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_state.dart
The _init_ can only run once (and is promised to succeed). This is not the case with _start_ method, so in case we need to recover from a failed start we need to call start again in a later time. This PR decouple these two functions and also makes sure we call start once internet connection is restored.
depends on https://github.com/breez/breez-sdk/pull/71
fixes #415 
fixes #416
> Separate start from init/recover/register

- lib/routes/home/account_page.dart
- lib/routes/home/widgets/app_bar/account_required_actions.dart
The lsp state is intialized when the node info is pushed from the sdk. We wait for this info before we emit the lsp state.
Ignoring null state in the UI ensures that we only consider a real state which prevents showing the LSP selection in cases where LSP is already selected.
Fixed #385
> Wait for initial node state before selecting lsp

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
This PR references issue #390. 
The app now displays Cloud Breez when installed on device. 
Please let me know if this name change is sufficient or if the scope for the renaming is larger?
> change app name to Cloud Breez #390

- lib/routes/home/widgets/payments_list/payment_item_avatar.dart
Addresses https://github.com/breez/c-breez/issues/414
Display +/- icons when payment item 
- has description or
- is sent with keysend or
- is a channel close payment
> Revise avatar icon logic

- ios/Podfile.lock
- lib/routes/home/widgets/payments_list/flip_transition.dart
- lib/routes/home/widgets/payments_list/payment_item.dart
- pubspec.lock
- pubspec.yaml
Fixes https://github.com/breez/c-breez/issues/404
- PaymentItem converted to StatefulWidget
- FlipTransition notifies PaymentItem when it's animation has completed to switch states,
- _createdWithin's return value now reflects it's name, previously it checked if it was not created within the duration
- New item added to PaymentsList doesn't force rebuild,
- The solution introduced in this PR will be obsolete if this is caused by a state management issue.
- There's a small delay after payment completion waiting for sync operations to finish, if this delay exceeds 10 seconds, the animation won't run.
> Notify PaymentItem when FlipTransition finishes

- lib/routes/home/widgets/app_bar/account_required_actions.dart
- lib/routes/home/widgets/bottom_actions_bar/send_options_bottom_sheet.dart
- lib/routes/withdraw_funds/withdraw_funds_address_page.dart
- lib/user_app.dart
This PR builds upon https://github.com/breez/c-breez/pull/367
The wrapper WithdrawFundsArguments isn't needed and WithdrawKind enum is now being used as argument.
> Refactor Withdraw Funds args

- lib/widgets/receivable_btc_box.dart
On a fresh setup (no channel open yet), creating an invoice would result in a fee warning like:
> A setup fee of 0.4% with a minimum of 2000 sats will be applied for receiving more than 0 sats.
The zero sat ending was due to the missing channel.
With this PR, the warning is
> A setup fee of 0.4% with a minimum of 2000 sats will be applied on the received amount.
Fixes https://github.com/breez/c-breez/issues/399
> Fix fee warning handling on receive

- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_destination_pubkey.dart
- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_expiration.dart
- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_preimage.dart
- lib/routes/home/widgets/payments_list/payment_details_dialog.dart
- lib/routes/home/widgets/payments_list/payment_item.dart
Upon reading #413 and seeing preimage widget was already in place on #434 I noticed type checking for LnPaymentDetails was wrong in two instances, which I figured out because I almost did the same mistake when implementing #432
- https://github.com/breez/c-breez/commit/44c0c9366428021bb75b7986743b2df009d4dade Extracted PaymentDetailsDialog to a widget as a continuation of #434 
- https://github.com/breez/c-breez/commit/d7f39b847beadf9b3fd7ba3f74a2946a12be4fe1 Use PaymentDetails.data to check against LnPaymentDetails
- https://github.com/breez/c-breez/commit/f3516b4b7573e8829992820bc02945703bbe814a Re-added missing pendingExpirationTimestamp `TODO` comment
> Correct how PaymentDetails data is accessed

- lib/bloc/swap_in/swap_in_bloc.dart
- lib/bloc/swap_in/swap_in_state.dart
- lib/routes/subswap/swap/swap_page.dart
- lib/routes/subswap/swap/widgets/inprogress_swap.dart
- lib/user_app.dart
- pubspec.lock
This PR fixed the user experience in 'Receive via BTC address' flow.
We now:
1. Allow only one inprogress swap at a time and at most one "unused" swap address at a time.
2. Aware of mempool transactions using polling the in progress swap.
depends on https://github.com/breez/breez-sdk/actions/runs/4015673422
> Swap in progress

- lib/bloc/input/input_bloc.dart
Remove case webview and appview in order to only react on lighting related stuff and not regular links in clipboard.
> no clipboard handling for appView and webView handling

- lib/bloc/user_profile/user_profile_bloc.dart
Related to https://github.com/breez/c-breez/issues/387.
Build fails due to color and animal being null when trying to set name.
fix by moving logic inside block where color and animal is set ref: https://github.com/breez/c-breez/pull/449#discussion_r1090037121. Do not think this should cause any issues or side effects.
> generate name inside bloc fix null issue

- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_description.dart
- lib/utils/extensions/payment_extensions.dart
Fix https://github.com/breez/c-breez/issues/461
Some data is not available on c breez, so we are not 100% equal; reference: https://github.com/breez/breezmobile/blob/232f1178d86b1b7152a03036ab33aafcf0c933a9/lib/bloc/account/account_model.dart#L774
> Replicate description logic from breez mobile on items where data is available

- ios/Podfile.lock
- lib/bloc/account/account_bloc.dart
- lib/bloc/account/payment_error.dart
- lib/bloc/account/payment_result.dart
- lib/bloc/input/input_bloc.dart
- lib/handlers/input_handler.dart
- lib/handlers/payment_result_handler.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/lnurl/lnurl_invoice_delegate.dart
- lib/routes/lnurl/payment/lnurl_payment_page.dart
- lib/routes/lnurl/payment/pay_response.dart
- lib/routes/lnurl/payment/success_action/success_action_data.dart
- lib/routes/lnurl/payment/success_action/success_action_dialog.dart
- lib/routes/lnurl/withdraw/lnurl_withdraw_dialog.dart
- lib/routes/spontaneous_payment/spontaneous_payment_page.dart
- lib/utils/exceptions.dart
- lib/utils/lnurl.dart
- lib/utils/payment_validator.dart
- lib/widgets/payment_dialogs/payment_request_info_dialog.dart
- pubspec.lock
- pubspec.yaml
- test/mock/breez_bridge_mock.dart
- test/utils/exceptions_test.dart
This draft PR is a continuation of #442 and addresses #403
- Differentiate between payment types when displaying payment result flushbar
- Replace SuccessActionData with SuccessAction from SDK
- Rename PaymentResultData -> PaymentResult
- Add payment results of lnurlPay, lnurlWithdraw, sendPayment and sendSpontaneousPayment to paymentResultStream
- Replace wait logic after receiving an event with emitting results with a delay and add logs(by @ademar111190)
- Ran dart format on changed files 
- We should have the same approach with formatting as we do on breez-sdk and not have any formatting changes in PRs
@ademar111190 and I think it's better to have a paymentResultStream on the SDK as we are already doing with other notifications(event, synced etc) Instead of managing it on AccountBloc. …
> Use SDK Models for payment result handling

- lib/routes/home/widgets/payments_list/dialog/closed_channel_payment_details.dart
- lib/routes/home/widgets/payments_list/dialog/payment_details_closed_channel_dialog.dart
- lib/routes/home/widgets/payments_list/dialog/tx_widget.dart
- lib/routes/home/widgets/payments_list/payment_details_dialog.dart
Initial work on: https://github.com/breez/c-breez/issues/410 showing the available info. The following data is not available yet at the greenlight SDK:
- closeChannelTx
- pendingExpirationHeight
- hoursToExpire
- remoteCloseChannelTx
How it looks like
> Closed channel dialog

- lib/bloc/account/credential_manager.dart
- lib/routes/dev/commands.dart
This PR addresses #477
Any non-existing parent paths are created while creating credentials & mnemonic phrase files.
Encountered error on a fresh install on iOS
```
2023-02-21T18:39:45.626265 :: E :: Main :: FlutterError: PathNotFoundException: Cannot open file, path = '/var/mobile/Containers/Data/Application/5C1A9724-9A20-4FFA-AFE8-E41906665739/Library/Caches/keysNKkDCQ/creds' (OS Error: No such file or directory, errno = 2) ::  :: 0 ::  :: 
PathNotFoundException: Cannot open file, path = '/var/mobile/Containers/Data/Application/5C1A9724-9A20-4FFA-AFE8-E41906665739/Library/Caches/keysNKkDCQ/creds' (OS Error: No such file or directory, errno = 2) :: 
#0      _checkForErrorResponse (dart:io/common.dart:42)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:364)
#2 …
```
> Create any non-existing parent paths while creating credentials & mnemonic phrase files

- lib/bloc/user_profile/user_profile_bloc.dart
- lib/models/user_profile.dart
- lib/routes/home/widgets/drawer/breez_navigation_drawer.dart
- lib/routes/home/widgets/drawer/home_drawer.dart
This issue addresses #499 
- Preferences tiles expansion state is now being persisted
- AppMode isn't being used at the moment but it was missing from updateProfile & UserProfileSettings.copyWith.
_This whole drawer logic needs another round of refactoring & simplification imo._
> Persist AppMode* and Preferences expansion state

- lib/routes/lnurl/lnurl_invoice_delegate.dart
The domain field was added to breez SDK, but it is missing on c-breez; I'm adding it to fix the build.
> Add domain to request data

- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/home/widgets/bottom_actions_bar/bottom_actions_bar.dart
- lib/routes/home/widgets/bottom_actions_bar/receive_options_bottom_sheet.dart
- lib/routes/home/widgets/bottom_actions_bar/send_options_bottom_sheet.dart
- lib/routes/home/widgets/qr_action_button.dart
- lib/routes/subswap/swap/swap_page.dart
Since it can take some time to establish a connection the the LSP we first checking if the user has selected a LSP. 
This should solve the issue where the QR button looks as if it disabled ref #489. 
I do not have to much experience with state management in flutter and are not sure if I have followed best practices and would appreciate if you could review this too.
We most likely can defer checking if the _swapper_ **Receive via BTC** is connected to the LSP until a later state of the app. Not sure where to do this.
> ensure selected LSP, defer checking connection to lsp

- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_success_action.dart
- lib/routes/home/widgets/payments_list/payment_details_dialog.dart
This PR is part of the changes for #496
Success action's data, whether it's message, url or aes is added to payment details dialog.
> Add Success Action information to Payment Details Dialog

- lib/routes/home/widgets/payments_list/dialog/shareable_payment_row.dart
- lib/routes/lnurl/payment/success_action/success_action_dialog.dart
This PR addresses https://github.com/breez/c-breez/issues/524
- Added content padding and title to SuccessActionDialog.
- Customized ShareablePaymentRow to match it's properties to [_URLRow](https://github.com/breez/breezmobile/blob/40d12a73d0adef0b4d50ad9fbb045469992b8136/lib/lnurl_success_action_dialog.dart#L78) in breezmobile.
> Match Breezmobile UI for Success Action Dialog

- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_ln_address.dart
- lib/routes/home/widgets/payments_list/payment_details_dialog.dart
This PR is part of 
- https://github.com/breez/c-breez/issues/497
LN Address information is added to Payment Details Dialog.
It seems like ln address information isn't added properly to payment info on SDK side or we need an additional parameter when paying to an ln address to notify SDK that ln address needs to be attached to the payment.
> Add LN Address information to Payment Details Dialog

- ios/Podfile.lock
- pubspec.lock
- pubspec.yaml
The upstream repo merged our changes so we can use it directly now.
Related: https://github.com/breez/c-breez/issues/521
> Uses clipboard watcher upstream repository

- lib/bloc/account/account_bloc.dart
- lib/handlers/input_handler.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/lnurl/auth/auth_response.dart
- lib/routes/lnurl/auth/lnurl_auth_handler.dart
- lib/routes/lnurl/auth/login_text.dart
- lib/routes/lnurl/lnurl_invoice_delegate.dart
- lib/routes/lnurl/payment/lnurl_payment_dialog.dart
- lib/routes/lnurl/payment/lnurl_payment_handler.dart
- lib/routes/lnurl/payment/lnurl_payment_info.dart
- lib/routes/lnurl/payment/lnurl_payment_page.dart
- lib/routes/lnurl/widgets/lnurl_page_result.dart
- lib/routes/lnurl/withdraw/lnurl_withdraw_dialog.dart
- lib/routes/lnurl/withdraw/lnurl_withdraw_handler.dart
- lib/routes/lnurl/withdraw/withdraw_response.dart
This PR addresses
- https://github.com/breez/c-breez/issues/59
Users will now be able to do `register`, `login`, `link` account, `auth` actions through LNURL-auth protocol with their wallet.
- Wallet duties are implemented for [LUD-04](https://github.com/lnurl/luds/blob/luds/04.md).
- Merged all LNURL related page results under LNURLPageResult,
- Refactored LNURL and LNURL Page Result handlers,
- Error dialog is shown after LNURL-Withdraw or LNURL-Auth fails to match breez mobile behavior
- Additional refactoring
> Support LNURL Auth base spec

- lib/routes/lnurl/lnurl_invoice_delegate.dart
- lib/routes/lnurl/widgets/lnurl_page_result.dart
- lib/routes/lnurl/withdraw/lnurl_withdraw_handler.dart
Fixes https://github.com/breez/c-breez/issues/571#issuecomment-1593286917
Our `if (result.hasError) {` check was routing the success flow and the else the error flow, so the fix is just invert the if/else.
I added more log that was useful to me understand the error during the process.
> Fix lnurlw

- lib/models/payment_minutiae.dart
- test/models/payment_minutiae_test.dart
Fixes https://github.com/breez/c-breez/issues/565
For some reason, I was expecting a map instead of the pattern `"[[\"text/plain\", \"lorem ipsum blah blah\"]]"`
> Fix metadata parsing

- lib/utils/exceptions.dart
Fixes #533 
Displays readable error message when the user insert an invalid recovery phrase.
> error message to restore node flow

- lib/handlers/connectivity_handler.dart
- lib/handlers/handler.dart
- lib/handlers/handler_context_provider.dart
- lib/handlers/input_handler.dart
- lib/handlers/payment_result_handler.dart
- lib/routes/home/home_page.dart
I have been catching several crashes originating from our handlers. The major cause is the `BuildContext` being hold by the handlers.
Here I'm fixing most of these crashes by using a `Handler` structure with an init/dispose structure and getting the context when needed and checking for its nullability.
> Fix build context crashes by improving how we make our handlers

- lib/widgets/payment_dialogs/payment_request_info_dialog.dart
This PR addresses 
- #547
Explanation for the changes are here: https://github.com/breez/c-breez/issues/547#issuecomment-1622154949
> The UI's code is practically the same between cBreez & Breezmobile, couldn't find the root cause but noticed `Column` alignments were behaving differently. We have a lot of `_addIfNotNull` logic, perhaps this difference is due to null safety. Will get back to investigating this later.
> 
> For now, I've applied a fix to programmatically allocate the free space around equally around dialog content. There's still a slight difference 🤏 Here's the comparison between cBreez(Dark theme) and Breezmobile(Blue theme) with this fix:
> 
>  [Screen.Recording.2023-07-05.at.19.49.13.mov ](https://github.com/breez/c-breez/assets/4012752/49c78167-b1f9-4245-ae7c-71bf4cdb2627 …
> Correct the payment request info dialog alignment

- lib/routes/home/widgets/bottom_actions_bar/receive_options_bottom_sheet.dart
> add divider above Buy Bitcoin

- lib/handlers/input_handler.dart
fixes #550 
The `_handlingRequest` did not reflect the the state after first scan since the value were not updated accordingly.
> fix handling request reflects state

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- pubspec.yaml
This PR is part of moving `breez-sdk/sdk-flutter` to it's own git repository: [breez-sdk-flutter](https://github.com/breez/breez-sdk-flutter).
- Update dependencies to latest resolvable
> Change source target of breez-sdk from local path to git repository

- ios/Runner/Info.plist
- lib/bloc/user_profile/default_profile_generator.dart
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/utils/date.dart
- pubspec.lock
- pubspec.yaml
Thank you @CS-HODL for the translations 🙏 
How it looks like:
|Home|Drawer menu|Bottom menu|
|---|---|---|
|![home](https://github.com/breez/c-breez/assets/1225438/f2232dca-ecb9-49d6-adf5-8b42fd2859ef)|![drawer menu](https://github.com/breez/c-breez/assets/1225438/b7322b47-9507-4d93-b96d-0e8ec0c3b5e8)|![bottom menu](https://github.com/breez/c-breez/assets/1225438/a9d5cbea-d61a-492f-af08-b9dfbf2bcd17)|
> Add Czech language support 🇨🇿🇪🇺

- ios/Podfile.lock
- lib/bloc/account/account_bloc.dart
- lib/bloc/account/payment_error.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/utils/payment_validator.dart
- pubspec.lock
- pubspec.yaml
Payments within inbound liquidity when LSP does not support channel openings are now allowed with this PR and a "Insufficient inbound liquidity $maxInboundLiquidity" error message is displayed when an invoice with an amount larger than inbound liquidity is attempted to be created.
Other changelist:
- Downgrade mobile_scanner to resolve warnings during Android build,
- Upgrade flutter_inappwebview as the issue that prevented this upgrade has been resolved
Todo:
- Add error message to Breez-Translations
> Allow payments within inbound liquidity when LSP does not support channel openings

- pubspec.lock
- pubspec.yaml
Bumped the archive package to a patched version https://github.com/breez/c-breez/security/dependabot/2.
> bump archive package

- lib/background/payment_hash_poller.dart
- lib/models/payment_minutiae.dart
- lib/routes/home/widgets/payments_list/dialog/closed_channel_payment_details.dart
- lib/routes/home/widgets/payments_list/dialog/payment_details_closed_channel_dialog.dart
- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_expiration.dart
- lib/routes/home/widgets/payments_list/payment_item_amount.dart
- lib/routes/home/widgets/payments_list/payment_item_subtitle.dart
Updating to reflect sdk integration https://github.com/breez/breez-sdk/pull/463.
@erdemyerebasmaz Do you think we need to change the logic to handle the cases where `PayementStatus` is failed?
> apply payment status

- ios/Podfile.lock
- lib/background/payment_hash_poller.dart
- lib/bloc/account/account_bloc.dart
- lib/models/payment_minutiae.dart
- lib/routes/home/widgets/payments_list/dialog/closed_channel_payment_details.dart
- lib/routes/home/widgets/payments_list/dialog/payment_details_closed_channel_dialog.dart
- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_expiration.dart
- lib/routes/home/widgets/payments_list/payment_item_amount.dart
- lib/routes/home/widgets/payments_list/payment_item_subtitle.dart
- lib/routes/home/widgets/payments_list/payment_item_title.dart
- lib/routes/home/widgets/payments_list/payments_list.dart
- lib/routes/lnurl/withdraw/lnurl_withdraw_dialog.dart
- pubspec.lock
- test/models/payment_minutiae_test.dart
This PR applies the mandatory changes introduced in
- Persist failed payments breez/breez-sdk#463
- Return invoice on successful lnurl-withdraw breez/breez-sdk#436
> Apply mandatory payment status and lnurlWithdraw changes

- lib/routes/home/widgets/bottom_actions_bar/send_options_bottom_sheet.dart
This pr removes the pasting logic of the [send_options_bottom_sheet.dart](https://github.com/breez/c-breez/compare/609-multiple-pasting?expand=1#diff-2e65547a4868cf3300a6a65a4fba5576d1ffabfbde9d4295925e68fdd6f61c9f) to mimic the behaviour of breezmobile. 
I believe this can be removed since the inputhandler handles the data if the user has something in their clipboard and in my opinion the UX is also better now. The user might want to manually write in an lighting address while having an invoice in the clipboard.
> remove pasting handling

- lib/bloc/backup/backup_bloc.dart
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/routes/dev/command_line_interface.dart
- lib/routes/dev/developers_view.dart
- lib/routes/dev/widget/command_list.dart
- lib/user_app.dart
This PR adds the listPeerChannels command introduced in
- https://github.com/breez/breez-sdk/pull/450
to command list.
- Rename file names to reflect class names
> Add listPeerChannels to command list

- lib/bloc/payment_options/form_validator.dart
- lib/bloc/payment_options/payment_options_bloc.dart
- lib/bloc/payment_options/payment_options_state.dart
- lib/config.dart
- lib/routes/payment_options/payment_options_page.dart
- lib/routes/payment_options/widget/excempt_fee_widget.dart
- lib/routes/payment_options/widget/exempt_fee_widget.dart
- lib/utils/preferences.dart
- pubspec.lock
- pubspec.yaml
- test/bloc/payment_options/form_validator_test.dart
- test/bloc/payment_options/payment_options_bloc_test.dart
- test/config_test.dart
- test/mock/breez_bridge_mock.dart
- test/mock/preferences_mock.dart
> let user specify exemptfee

- lib/routes/home/widgets/bottom_actions_bar/enter_payment_info_dialog.dart
Fixes #619 
Removes `SingleChildScrollView` from _[enter_payment_info_dialog.dart](https://github.com/breez/c-breez/compare/619-bad-ui-when-sending?expand=1#diff-d2ec47035ee8d1efd77b5eee62cd33f0dc6908d004e23895a19c78ffc81fb9c9)_  which will overflow the widget for small screens. Since we have the same design in breezmobile and have not heard any complaints I think this should be fine.
> remove SingleChildScrollView to behave like breezmobile

- android/app/build.gradle
- Reverts the sign-in config for release made on my last PR https://github.com/breez/c-breez/pull/623
- @roeierez will be signing release builds for the store manually
- Release builds made by CI are using the default debug config
- Keep the debug (renamed to development) config
- This keeps the ability of the team to make debug builds with working integrations
Manually triggered https://github.com/breez/c-breez/actions/runs/6407131491 to see if everything is working
> Revert signing config for release keeping the development (debug)

- lib/routes/lnurl/withdraw/lnurl_withdraw_dialog.dart
> Fix handling of LNURLw response types

- lib/routes/home/widgets/bottom_actions_bar/bottom_actions_bar.dart
- lib/routes/home/widgets/bottom_actions_bar/receive_options_bottom_sheet.dart
Fixes #642 
In order to make the UX for receiving and sending a bit smoother we can defer waiting for account state until the validation of the payment and not when initialing the payment. This should make it better for users if the internet speed is slow.
> defer account state checking

- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_state.dart
- lib/bloc/backup/backup_state.dart
- lib/bloc/lsp/lsp_state.dart
- lib/routes/home/widgets/app_bar/account_required_actions.dart
- lib/routes/initial_walkthrough/initial_walkthrough.dart
Fixes: https://github.com/breez/c-breez/issues/647
- Clean install c-breez
- Start a new wallet (Let's breez! option)
- You should see a warning icon at the top right
- This warning should trigger the verify seed phrase flow
- Clean install c-breez
- Restore a wallet (Restore from backup option)
- You should not see a warning icon at the top right
- (We consider the phrase verified as you just restored it)
> Verify seed phrase

- lib/bloc/account/account_bloc.dart
- lib/routes/create_invoice/create_invoice_page.dart
Add the cheapest known feerate as argument to `createInvoice`.
Fixes #643
> Add fee params arg to createInvoice

- android/app/src/main/AndroidManifest.xml
How to test:
- Test on:
- Android prior to 11
- Android 11 and/or higher
- Go to Receiver
- Buy Bitcoin
- A buy bitcoin flow should start using the Moonpay web app
- Buy some sats
- Wait a few minutes (block mining time) 
- The sats should be available at your LN wallet
> Fix moonpay buy flow (adding query for opening links on Android 11+)

- lib/bloc/account/account_bloc.dart
- lib/bloc/input/input_bloc.dart
- lib/bloc/input/input_data.dart
- lib/bloc/input/input_printer.dart
- lib/bloc/input/input_source.dart
- lib/bloc/input/input_state.dart
- lib/handlers/input_handler.dart
- lib/main.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/home/widgets/bottom_actions_bar/enter_payment_info_dialog.dart
- lib/routes/home/widgets/qr_action_button.dart
- lib/routes/lnurl/lnurl_invoice_delegate.dart
- test/bloc/input/input_bloc_test.dart
Fixes: https://github.com/breez/c-breez/issues/570
- Generates a Bitcoin address QR code
- Try different address formats (1... 3... bc1...)
-  Try adding the amount and leaving it empty
- Opens c-breez and then open the camera scanner
- The app should recognize the QR code and open the Send to BTC address page
- The address and the amount should be correctly filled with the data you added on the QR code
> Trigger send to BTC address flow when camera reads a BTC address

- lib/routes/home/widgets/dashboard/fiat_balance_text.dart
Hide the fiat amount showed at home page if the sats amount is zero
<details>
<summary>Screenshots</summary>
|Before|After|
|---|---|
|![Screenshot_20231011_101904-min](https://github.com/breez/c-breez/assets/1225438/a695425d-3957-413a-89b8-547dd7098335)|![Screenshot_20231011_102656-min](https://github.com/breez/c-breez/assets/1225438/36b1bd9f-e51d-4d33-bd04-1ffc7f1222f8)|
</details>
- Create a new wallet or get wallet without any sats
- It should not show the fiat value
- Using a wallet that has sats
- It should show the fiat value
> Doesn't show the fiat amount when the sats balance is zero

- lib/bloc/account/account_bloc.dart
- lib/bloc/account/credentials_manager.dart
- lib/routes/dev/developers_view.dart
- pubspec.lock
- pubspec.yaml
implements https://github.com/breez/c-breez/issues/626
Should the file be written as bytes or string?
>  allow export of static backup

- lib/models/payment_minutiae.dart
- lib/routes/home/widgets/payments_list/dialog/closed_channel_payment_details.dart
fixes #536 
Add funding and closing txid to paymentMinutiae if available.
Remove the displaying of remote and local commitment transactions for pending closes until later.
Use blockexplorer specified in config.
> add funding and closing transaction to paymentMinutiae

- analysis_options.yaml
- android/settings.gradle
- lib/logger.dart
- pubspec.lock
- pubspec.yaml
How the log looks like:
```
[Logger] {FINE} (2023-10-11T12:17:10.440217Z) : Logging initialized, app build on main at commit 06b48d40ed9e7093efb0640ad5846ab61e0e2038
```
No QA needed
> Add git branch and commit when log is initialized to help debug

- lib/logger.dart
- pubspec.lock
- pubspec.yaml
How the log looks like:
```
[Logger] {INFO} (2023-10-19T12:34:51.610359Z) : Logging initialized, app build on main at commit ced812d6a909f491406cbeca7c4c93400c221a54
[Logger] {INFO} (2023-10-19T12:34:51.728177Z) : Device info:
[Logger] {INFO} (2023-10-19T12:34:51.729039Z) : product: lineage_jasmine_sprout
[Logger] {INFO} (2023-10-19T12:34:51.731083Z) : supportedAbis: [arm64-v8a, armeabi-v7a, armeabi]
[Logger] {INFO} (2023-10-19T12:34:51.731554Z) : serialNumber: unknown
[Logger] {INFO} (2023-10-19T12:34:51.902439Z) : displayMetrics: {xDpi: 403.4110107421875, widthPx: 1080.0, heightPx: 2160.0, yDpi: 403.4110107421875}
[Logger] {INFO} (2023-10-19T12:34:51.903153Z) : supported32BitAbis: [armeabi-v7a, armeabi]
[Logger] {INFO} (2023-10-19T12:34:51.903489Z) : display: …
```
> Add device info to the log

- lib/bloc/input/input_bloc.dart
- test/bloc/input/input_bloc_test.dart
- test/mock/breez_bridge_mock.dart
- test/unit_logger.dart
Currently, we are waiting for a node state before starting to listen to the clipboard, it can happen that a device emits the clipboard earlier than others and we end in a state where we miss such an event.
I'm changing the logic of the InputBloc initialization to start watching inputs immediately and wait for a node state once it receives an event, so we don't lose any events.
As the node stream is controlled by a behavior subject, we get the state immediately once the first item is emitted so there is no difference in behavior to what we have today; on the other hand, I believe this change will solve the issue https://github.com/breez/c-breez/issues/678 
- Copy a lnurl to your clipboard
- Goes to c-breez app
- It should be handled
- Test with the app open and closed
> Immediately listen inputs and move the wait for node state after event

- .github/workflows/CI.yml
- lib/background/payment_hash_poller.dart
- lib/bloc/account/account_bloc.dart
- lib/bloc/account/credentials_manager.dart
- lib/bloc/buy_bitcoin/moonpay/moonpay_bloc.dart
- lib/bloc/refund/refund_bloc.dart
- lib/bloc/reverse_swap/reverse_swap_bloc.dart
- lib/bloc/swap_in_progress/swap_in_progress_bloc.dart
- lib/bloc/sweep/sweep_bloc.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/lnurl/auth/lnurl_auth_handler.dart
- lib/routes/lnurl/payment/lnurl_payment_dialog.dart
- lib/routes/lnurl/payment/lnurl_payment_handler.dart
- lib/routes/lnurl/payment/lnurl_payment_page.dart
- lib/routes/lnurl/withdraw/lnurl_withdraw_dialog.dart
- lib/routes/spontaneous_payment/spontaneous_payment_page.dart
depends on https://github.com/breez/breez-sdk/pull/497
> switch to use amountMsat for upcomming sdk release.

- lib/user_app.dart
We have been passing sensitive data through `RouteSettings` which was being logged.
This PR removes these data and keeps only the route name.
No QA is Needed.
P.S. Thanks @ubbabeck for noticing the problem.
> Make route logging logs just the route name to avoid logging sensitive data shared through route arguments

- lib/bloc/fee_options/fee_options_bloc.dart
- lib/routes/withdraw/reverse_swap/confirmation_page/reverse_swap_confirmation_page.dart
- lib/routes/withdraw/sweep/confirmation_page/sweep_confirmation_page.dart
- pubspec.lock
Related https://github.com/breez/breez-sdk/pull/294
- Close your channels
- Wait for the triangle showing unexpected funds appear at the top right of home page
- It can take some hours
- You can close the app and back later
- Go through the flow sending the sats to a btc wallet
- At the processing fee speed, choose one of the options
- write down the fee and value you should receive at you address
- Confirm the transaction and wait for the sats appear at your wallet
- It can take some hours
- You can close the app and back later
- Check if the value you received and the fee paid is the same
- It can be a few sats different from the forecasted
- something like 2 sats of difference is expected.
> Fee calculation and presentation

- lib/routes/home/widgets/payments_list/dialog/shareable_payment_row.dart
Pull changes from https://github.com/breez/breezmobile/pull/1242
> Allow two lines for shareable payment row

- lib/bloc/rev_swap_in_progress/rev_swap_in_progress_bloc.dart
- lib/bloc/swap_in_progress/swap_in_progress_bloc.dart
- lib/routes/subswap/swap/swap_page.dart
When we are creating a swap and we're polling the swap address it refreshes the address every 5 seconds to see if it has been used. We emit a new state every 5 seconds. 
This works when we're in the swap page, but when the we go back to the home page close() is called, but the method might still be running and thus causing a bad state. 
To avoid this behaviour I suggest that we add a check if the bloc is closed before attempting to emit new states.
> swap page emit state when closed

- lib/routes/dev/command_line_interface.dart
- lib/routes/dev/widget/command_list.dart
Added the `stop` dev command.
Note: as the command will stop the remote note before it will be able to respond to the gRPC call, it will throw an error. See https://github.com/breez/breez-sdk/blob/89af9b4e1fb66ebb06294c709d218bf5568fab57/libs/sdk-core/src/greenlight/node_api.rs#L1362-L1368
> Add dev command: stop

- android/app/src/main/AndroidManifest.xml
This causes issues on older devices (tested on Pixel 3a / Android 12 / API 32).
> Disable Impeller

- ios/Breez Notification Service Extension/BreezManager.swift
- ios/Breez Notification Service Extension/NotificationService.swift
This PR simplifies the notification extension logic and prepares it to other upcoming types of background tasks (such as lnurlpay)
For each notification type a proper task is created and being started to handle that notification end to end.
Also found out that the notification is not invoked in parallel. If there are multiple payments in parallel, the notifications are queued and invoked one after another so no need to code for the case where we can several notifications for the same instance.
I also noticed we don't need the payment hash poller, we can just wait for payment received event which seems to be reliable enough.
fixed #751
> Single extension instance

- test/mock/breez_bridge_mock.dart
These fields were removed from the sdk in https://github.com/breez/breez-sdk/pull/780
> remove outdated fields from LspInformation

- android/app/build.gradle
- ios/Breez Notification Service Extension/Info.plist
- ios/Runner/Info.plist
- troubleshooting.md
`--dart-define-from-file` had the ability to get access to provided key-value pairs in gradle and plist but it was _silently_ removed with **Flutter 3.19**. It was not considered a breaking change and was not documented in release notes by Flutter team.
I was not able to catch this on my builds, perhaps due to cache issues. @dangeross encountered this issue and found the related issues on this information & a [workaround](https://github.com/flutter/flutter/issues/142976#issuecomment-1949602247).
- Apply the workaround so that the dart defined variables are available from `gradle` 448d34a29bd99498e649e55c44791c26173bd372
- The iOS counterpart isn't implemented as we're not using environment variables on our Notification Service App Extension, they are accessed through shared Keychain
- In …
> Environment variables workaround for Flutter 3.19

- lib/bloc/buy_bitcoin/moonpay/moonpay_bloc.dart
This PR addresses breaking changes from swap events.
Breez SDK PR:
- https://github.com/breez/breez-sdk/pull/811
> Deprecate SwapStatus.Expired

- lib/bloc/reverse_swap/reverse_swap_bloc.dart
- lib/routes/dev/developers_view.dart
Relies on: 
- https://github.com/breez/breez-sdk/pull/797
> Allow rescanning swaps from Developers View

- lib/routes/lnurl/payment/lnurl_payment_page.dart
- lib/routes/subswap/swap/widgets/deposit_widget.dart
Fixes #753
The invoice amount was considered an incoming payment during validation by mistake.
> Use the correct payment validation for LNURL payments

- lib/logger.dart
The `CONFIG` level resulted in logging the sending and receiving of gRPC data frames, which is spamming the logs:
```
[BreezSdk] {CONFIG} (2024-03-13T09:51:00.634293Z) : send frame=Data { stream_id: StreamId(1) }
[BreezSdk] {CONFIG} (2024-03-13T09:51:00.735160Z) : send frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }
[BreezSdk] {CONFIG} (2024-03-13T09:51:01.103566Z) : received frame=Settings { flags: (0x1: ACK) }
[BreezSdk] {CONFIG} (2024-03-13T09:51:01.117228Z) : received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
[BreezSdk] {CONFIG} (2024-03-13T09:51:01.157191Z) : received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 73 }
[BreezSdk] {CONFIG} (2024-03-13T09:51:01.222232Z) : received …
```
> Reduce default log level from `CONFIG` to `INFO`

- android/app/src/main/kotlin/com/cBreez/client/BreezForegroundService.kt
- ios/Breez Notification Service Extension/NotificationService.swift
- ios/Runner.xcodeproj/project.pbxproj
- lib/bloc/payment_options/form_validator.dart
- lib/bloc/payment_options/payment_options_bloc.dart
- lib/bloc/payment_options/payment_options_state.dart
- lib/routes/payment_options/payment_options_page.dart
- lib/routes/payment_options/widget/channel_setup_fee_limit.dart
- lib/utils/preferences.dart
- test/bloc/payment_options/payment_options_bloc_test.dart
- test/mock/preferences_mock.dart
Closes #777
This PR allows users to set a "`Automatic channel setup fee limit"` through **Lightning Fees** page to be able to receive LNURL payments that require a channel setup where the fees fall within that limit. 
On C-Breez, this feature is **enabled** & set to **5000 sats** by default.
Breez SDK PR:
- https://github.com/breez/breez-sdk/pull/833
- If the invoice can not be created due to not enough fees to cover the channel respond with error.
@dangeross @roeierez
Currently, on the extensions we're getting the value from shared preferences but this approach is not directly compatible with extension plugin. To be able to make this compatible with extension plugin, I think a good approach would be:
- Make this part of SDK `Config`
- Should be disabled and set to 0 by default imo, I'm …
> LNURL-Payment: Channel setup fee limit

- android/app/src/main/resources/tinylog.properties
- ios/Breez Notification Service Extension/NotificationService.swift
This PR is a continuation of #817 and re-adds `tinylog.properties` which was overlooked when logging library choices got abstracted from notification service extensions.
> Reduce default log level from `DEBUG` to `INFO` on notification service extensions

- ios/Runner.xcodeproj/project.pbxproj
- lib/bloc/payment_options/payment_options_bloc.dart
- lib/routes/payment_options/widget/actions_fee.dart
- lib/utils/preferences.dart
This PR changes the `PaymentOptionsBloc` to set the initial default shared preferences (in iOS also to the app group UserDefaults) if they are currently not stored. This allows the notification service extension to get the default values from shared preferences.
> Set initial default shared preferences

- lib/models/fee_options/fee_option.dart
- lib/routes/get-refund/refund_confirmation_page.dart
- lib/routes/withdraw/redeem_onchain_funds/confirmation_page/redeem_onchain_funds_confirmation.dart
- lib/routes/withdraw/widgets/fee_chooser/widgets/fee_chooser_header.dart
Corrects the fee affordability calculations for refund & redeem onchain.
- Checks if refund amount is greater or equal to tx fees,
- Checks if onchain balance is greater or equal to redeem onchain amount.
I'm not satisfied with the shared Fee widgets & models on swap/reverse swap and plan to go over them to make them more robust at a later date.
> Correct fee affordability calculations for swaps

- ios/Podfile.lock
- lib/bloc/account/account_bloc.dart
- lib/bloc/connectivity/connectivity_bloc.dart
- lib/bloc/connectivity/connectivity_state.dart
- lib/bloc/lsp/lsp_bloc.dart
- lib/bloc/security/security_bloc.dart
- lib/handlers/connectivity_handler.dart
- pubspec.lock
- pubspec.yaml
Updates dependencies to latest & resolves breaking changes introduced in:
- [connectivity_plus 6.0.1](https://pub.dev/packages/connectivity_plus/changelog#601)
- **BREAKING FEAT**(connectivity_plus): support multiple connectivity types at the same time ([#2599](https://github.com/fluttercommunity/plus_plugins/issues/2599)). ([5b477468](https://github.com/fluttercommunity/plus_plugins/commit/5b4774683d6e186fbd69cf4208302221f52aa54d))
- [local_auth 2.2.0](https://pub.dev/packages/local_auth/changelog#220)
- Switches endorsed iOS implementation to local_auth_darwin.
- Clients directly importing local_auth_ios for auth strings should switch dependencies and imports to local_auth_darwin. No other change is necessary.
> Update dependencies to latest

- lib/bloc/account/account_bloc.dart
- lib/handlers/node_connectivity_handler.dart
- lib/routes/home/home_page.dart
- lib/routes/initial_walkthrough/initial_walkthrough.dart
This PR introduces bug fixes & improvements to node connection failures.
- Do not navigate to home page if registration fails 83536a2381d1117ba00ce671de7435caf35aacdf
- Throw errors during connecting to SDK
- Create NodeConnectivityHandler to notify the user when their node is disconnected 831f80669f77b40de2bce3b0b6f59270df6c3ce3 
- Display a flushbar on top with a manual retry option*
- Change `ConnectionStatus` immediately on calling connect 91bf6604d31877134776cd95ffa3787e64b3ca43
- Connection status changes will reflect without delay on reconnect attempts
> Handle node related connectivity issues

- lib/bloc/refund/refund_bloc.dart
- lib/bloc/refund/refund_state.dart
- lib/routes/get-refund/get_refund_page.dart
closes #834 
Refundable list is refreshed once node connects on start up and after on receiving swap events for swaps with Refundable & Completed status.
Breez SDK PR: 
- https://github.com/breez/breez-sdk/pull/876
> Listen to swap events to refresh refundables

- lib/bloc/input/input_bloc.dart
- lib/bloc/input/input_printer.dart
- lib/bloc/input/input_state.dart
- lib/logger.dart
- lib/main.dart
- lib/routes/qr_scan/widgets/qr_scan.dart
- lib/utils/sdk_fields/serializer_helper.dart
- test/bloc/input/input_bloc_test.dart
This PR addresses the issue where large logs that are truncated. They are now printed in chunks.
- Add helper method `printWrapped` to log large strings,
- Add helper methods to print certain SDK classes
- `SwapInfo` & `OpeningFeeParams`. These will be used on in progress reverse swap/swap bloc revision PR.
- Get rid of `InputPrinter` and make it's methods globally accessible
- Add `inputDataToString` helper method
> Temporary solutions to log large strings & certain SDK classes

- lib/bloc/network/network_settings_bloc.dart
- lib/config.dart
- lib/routes/get-refund/widgets/refund_item_action.dart
- lib/routes/home/widgets/payments_list/dialog/closed_channel_payment_details.dart
- lib/routes/withdraw/reverse_swap/in_progress/reverse_swap_in_progress.dart
Applies minimum required changes for Breez SDK PR:
- https://github.com/breez/breez-sdk/pull/898
These changes do integrate the fallback behavior but we still rely on "https://mempool.space/" to display the transactions onchain on the UI.
That is until the user sets a Mempool API URL of their choice from **Preferences** -> **Network**.
> Set "https://mempool.space/" as default mempool url on app layer

- lib/bloc/refund/refund_bloc.dart
- lib/bloc/rev_swap_in_progress/rev_swap_in_progress_bloc.dart
- lib/bloc/reverse_swap/reverse_swap_bloc.dart
- lib/routes/withdraw/reverse_swap/in_progress/reverse_swap_in_progress.dart
- lib/routes/withdraw/reverse_swap/in_progress/reverse_swaps_in_progress_page.dart
- Refactor reverse swap in progress bloc 
- Increased timer interval to 30 seconds
- Ensure the bloc isn't closed when emitting states
- Log fee rate for prepared onchain payment
- Refactor `ReverseSwapInProgress` widget (fixes #855)
- > `ReverseSwapInProgressBloc` is not accessible from `ReverseSwapInprogress` and it caused UI to crash when we tried fetching lockupTxid via:
>
> `final lockTxID = context.watch<sdk.ReverseSwapInfo>().lockupTxid;`
>
> `lockupTxid` is now passed to child widgets from `ReverseSwapPage` and not looked up from provider using `context.watch()`
- If there was a race condition and there were multiple swaps in progress, the UI repeated the waiting confirmation message for each TX. The waiting confirmation message is now displayed as header on …
> Refactor Reverse Swap In Progress

- lib/routes/subswap/swap/swap_page.dart
- lib/routes/subswap/swap/widgets/swap_error_message.dart
- lib/routes/withdraw/reverse_swap/in_progress/reverse_swap_in_progress.dart
- lib/utils/exceptions.dart
Fixes #852 
- `FrbAnyhowException` messages are retrieved by exception type instead of relying on regex 
- `transport error` messages are converted to generic network messages for nested exceptions. 
- All `transport error`'s across the app should be beautified now.
- We now display a generic network error message on "Deposit to BTC Address" page.
> Display a generic error message on Deposit to BTC Address page

- ios/Breez Notification Service Extension/PrivacyInfo.xcprivacy
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/PrivacyInfo.xcprivacy
This PR adds privacy manifest files to each target that details use of personal data (not applicable) or usage of APIs that require a reason for its use (UserDefaults API). Listed are read/write of the UserDefaults of the app itself and apps/extensions using the same app group.
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
> Add privacy manifest files

- lib/routes/withdraw/reverse_swap/reverse_swap_form.dart
- lib/routes/withdraw/reverse_swap/reverse_swap_form_page.dart
- lib/routes/withdraw/reverse_swap/reverse_swap_page.dart
- lib/routes/withdraw/widgets/withdraw_funds_available_btc.dart
fixes #866
- Do not display max swap amount as **Balance** and let UI form validation fail. Only use max swap amount for "Use All Funds" feature
- Padding and text style now matches Breez mobile
- Reduce clutter on `ReverseSwapPage` by moving parts of it logic to `ReverseSwapFormPage` & `ReverseSwapForm`
> Display balance on "Send to BTC Address" page at all times

- lib/routes/buy_bitcoin/moonpay/moonpay_page.dart
- lib/routes/dev/developers_view.dart
- lib/routes/home/account_page.dart
- lib/routes/home/widgets/payments_filter/calendar_dialog.dart
- lib/theme/breez_dark_theme.dart
- lib/theme/breez_light_theme.dart
- lib/theme/theme_extensions.dart
I'm not sure when did Flutter changed this but overriding ThemeData is no longer enough to override date picker theme. It now uses colorScheme & datePickerTheme of ThemeData.
- Added datePickerTheme to ThemeData
> Address UI differences between Breez mobile

- test/mock/breez_bridge_mock.dart
Addresses breaking changes from Breez SDK PR:
- https://github.com/breez/breez-sdk/pull/918
Adds required `allowNostr` field to mock `LnUrlPayRequestData` used on tests.
> Add required `allowsNostr` field to `LnUrlPayRequestData`

- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_expiration.dart
Closes #874 
- Display expiration field only if pending expiration block is larger than current block height
> Do not display expiration field for payments that are no longer pending

- lib/bloc/rev_swap_in_progress/rev_swap_in_progress_bloc.dart
- lib/bloc/swap_in_progress/swap_in_progress_bloc.dart
> Address LateInitializationError on swap timers

- lib/routes/fiat_currencies/fiat_currency_settings.dart
- lib/routes/initial_walkthrough/mnemonics/widgets/restore_form.dart
- pubspec.lock
- pubspec.yaml
Updated dependencies that are not compatible with Flutter 3.22.
- Forked `drag_and_drop_list` and addressed issues [here](https://github.com/breez/DragAndDropLists/commit/38cc3155a6161730b4ec476d781873afb7ec4846).
- Note: This plugin is no longer maintained.
- Addressed breaking changes on our fork of `flutter_typeahead` [here](https://github.com/breez/flutter_typeahead/commit/4a494322762af9f30820f3c63aba784d46b86b69).
> Flutter 3.22  - Dependencies breaking build

- ios/Podfile.lock
- lib/app_config.dart
- lib/services/deep_links.dart
- pubspec.lock
- pubspec.yaml
- test/mock/breez_bridge_mock.dart
[![Run CI](https://github.com/breez/c-breez/actions/workflows/CI.yml/badge.svg?branch=gl-new-creds)](https://github.com/breez/c-breez/actions/workflows/CI.yml)
---
This PR applies breaking changes from:
- https://github.com/breez/breez-sdk/pull/985
@roeierez, @JssDWt: Do we need to use the new `nodeCredentials` API somewhere on the app?
- Update dependencies to latest
- Ignore Firebase Dynamic Links deprecation warning
- Note: Firebase Dynamic Links is deprecated and the service will shut down on August 25, 2025. Please see our Dynamic Links Deprecation FAQ documentation > for guidance on alternative solutions and migration options: https://firebase.google.com/support/dynamic-links-faq.
> Move greenlight to new credential mechanism

- lib/routes/lnurl/payment/lnurl_payment_handler.dart
This PR applied changes from
- https://github.com/breez/breez-sdk/pull/1039
so that callback domain validation is bypassed for LNURL-Pay success action URL's and callback domain and C-Breez behavior is the same with Breezmobile.
> Allow payments to be made if there's a callback domain mismatch with SuccessAction URL

- lib/bloc/reverse_swap/reverse_swap_bloc.dart
- lib/routes/withdraw/redeem_onchain_funds/redeem_onchain_funds_page.dart
- lib/routes/withdraw/reverse_swap/reverse_swap_form.dart
- lib/routes/withdraw/reverse_swap/reverse_swap_page.dart
- lib/routes/withdraw/widgets/withdraw_funds_amount_text_form_field.dart
This PR applies the changes in
- https://github.com/breez/breez-sdk/issues/1037
`minSat` & `maxSat` are no longer returned as 0 when user has insufficient balance for the payment from `onchainPaymentLimits`, a new field `maxPayableSat` is added which denotes the maximum amount the node can send with it's current channels & local balance.
If the payment amount falls within min-max limits, it is then compared against `maxPayableSat` to validate if the payment can be made.
> Compare payment amount against `maxPayableSat` instead of `balanceSat`

- ios/Podfile
- ios/Podfile.lock
- pubspec.lock
This PR addresses crashes specific to iOS 15.x due to conflict between system-provided & our own sqlite3 implementation.
> iOS 15.x crash

- lib/routes/dev/command_line_interface.dart
Should fix https://github.com/breez/c-breez/issues/902
> use raw text as command result

- lib/routes/withdraw/widgets/fee_chooser/widgets/fee_breakdown.dart
The tx fee for a swap-in should be deducted from the amount. The sender amount is `amountSat` here.
> fix the swap-in refund sender amount
